name: passwordgenerator
description: "Random Password Generator"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_window_close: ^1.3.0
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  fluikit:
    git:
      url: https://github.com/RaulCatalinas/Fluikit.git
      ref: main
  flutter_themed: ^1.0.0+3
  logkeeper: ^1.2.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter-latin-400-normal.ttf
          weight: 400
          style: normal

flutter_launcher_icons:
  image_path: "assets/icon.png"
  image_path_ios: "assets/icon_ios.jpg"
  min_sdk_android: 24
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  linux:
    generate: true
  android: "launcher_icon"
  ios: true
